<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CleanSheet;

class CleanSheetsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cleanSheets = [
            [
                'goalkeeper_name' => 'Patrick Matasi',
                'team_name' => 'Vipers Academy',
                'position' => 1,
                'clean_sheets' => 12,
                'appearances' => 20,
                'clean_sheet_percentage' => 60.00,
                'saves' => 68,
                'goals_conceded' => 15,
                'save_percentage' => 81.93,
                'penalties_saved' => 2,
                'penalties_faced' => 3,
                'minutes_played' => 1800,
                'shots_faced' => 156,
                'shots_on_target_faced' => 83,
                'shots_faced_per_game' => 7.80,
                'nationality' => 'Kenyan',
                'age' => 28,
                'height_cm' => 185.50,
                'dominant_hand' => 'Right',
                'is_vipers_player' => true,
            ],
            [
                'goalkeeper_name' => 'Boniface Onyango',
                'team_name' => 'Gor Mahia FC',
                'position' => 2,
                'clean_sheets' => 10,
                'appearances' => 20,
                'clean_sheet_percentage' => 50.00,
                'saves' => 72,
                'goals_conceded' => 18,
                'save_percentage' => 80.00,
                'penalties_saved' => 1,
                'penalties_faced' => 2,
                'minutes_played' => 1800,
                'shots_faced' => 162,
                'shots_on_target_faced' => 90,
                'shots_faced_per_game' => 8.10,
                'nationality' => 'Kenyan',
                'age' => 30,
                'height_cm' => 188.00,
                'dominant_hand' => 'Right',
                'is_vipers_player' => false,
            ],
            [
                'goalkeeper_name' => 'Duncan Ochieng',
                'team_name' => 'AFC Leopards',
                'position' => 3,
                'clean_sheets' => 8,
                'appearances' => 20,
                'clean_sheet_percentage' => 40.00,
                'saves' => 65,
                'goals_conceded' => 20,
                'save_percentage' => 76.47,
                'penalties_saved' => 0,
                'penalties_faced' => 1,
                'minutes_played' => 1800,
                'shots_faced' => 148,
                'shots_on_target_faced' => 85,
                'shots_faced_per_game' => 7.40,
                'nationality' => 'Kenyan',
                'age' => 26,
                'height_cm' => 182.00,
                'dominant_hand' => 'Right',
                'is_vipers_player' => false,
            ],
            [
                'goalkeeper_name' => 'Timothy Odhiambo',
                'team_name' => 'Tusker FC',
                'position' => 4,
                'clean_sheets' => 7,
                'appearances' => 20,
                'clean_sheet_percentage' => 35.00,
                'saves' => 58,
                'goals_conceded' => 22,
                'save_percentage' => 72.50,
                'penalties_saved' => 1,
                'penalties_faced' => 1,
                'minutes_played' => 1800,
                'shots_faced' => 136,
                'shots_on_target_faced' => 80,
                'shots_faced_per_game' => 6.80,
                'nationality' => 'Kenyan',
                'age' => 29,
                'height_cm' => 186.00,
                'dominant_hand' => 'Left',
                'is_vipers_player' => false,
            ],
            [
                'goalkeeper_name' => 'Collins Okoth',
                'team_name' => 'KCB FC',
                'position' => 5,
                'clean_sheets' => 6,
                'appearances' => 20,
                'clean_sheet_percentage' => 30.00,
                'saves' => 62,
                'goals_conceded' => 24,
                'save_percentage' => 72.09,
                'penalties_saved' => 0,
                'penalties_faced' => 2,
                'minutes_played' => 1800,
                'shots_faced' => 140,
                'shots_on_target_faced' => 86,
                'shots_faced_per_game' => 7.00,
                'nationality' => 'Kenyan',
                'age' => 25,
                'height_cm' => 184.00,
                'dominant_hand' => 'Right',
                'is_vipers_player' => false,
            ],
            [
                'goalkeeper_name' => 'Brian Bwire',
                'team_name' => 'Mathare United',
                'position' => 6,
                'clean_sheets' => 5,
                'appearances' => 20,
                'clean_sheet_percentage' => 25.00,
                'saves' => 55,
                'goals_conceded' => 26,
                'save_percentage' => 67.90,
                'penalties_saved' => 1,
                'penalties_faced' => 1,
                'minutes_played' => 1800,
                'shots_faced' => 132,
                'shots_on_target_faced' => 81,
                'shots_faced_per_game' => 6.60,
                'nationality' => 'Kenyan',
                'age' => 27,
                'height_cm' => 181.00,
                'dominant_hand' => 'Right',
                'is_vipers_player' => false,
            ],
            [
                'goalkeeper_name' => 'Michael Otieno',
                'team_name' => 'Sofapaka FC',
                'position' => 7,
                'clean_sheets' => 4,
                'appearances' => 20,
                'clean_sheet_percentage' => 20.00,
                'saves' => 48,
                'goals_conceded' => 28,
                'save_percentage' => 63.16,
                'penalties_saved' => 0,
                'penalties_faced' => 1,
                'minutes_played' => 1800,
                'shots_faced' => 124,
                'shots_on_target_faced' => 76,
                'shots_faced_per_game' => 6.20,
                'nationality' => 'Kenyan',
                'age' => 24,
                'height_cm' => 183.00,
                'dominant_hand' => 'Right',
                'is_vipers_player' => false,
            ],
            [
                'goalkeeper_name' => 'David Owino',
                'team_name' => 'Ulinzi Stars',
                'position' => 8,
                'clean_sheets' => 3,
                'appearances' => 20,
                'clean_sheet_percentage' => 15.00,
                'saves' => 52,
                'goals_conceded' => 30,
                'save_percentage' => 63.41,
                'penalties_saved' => 1,
                'penalties_faced' => 2,
                'minutes_played' => 1800,
                'shots_faced' => 130,
                'shots_on_target_faced' => 82,
                'shots_faced_per_game' => 6.50,
                'nationality' => 'Kenyan',
                'age' => 23,
                'height_cm' => 180.00,
                'dominant_hand' => 'Right',
                'is_vipers_player' => false,
            ],
            [
                'goalkeeper_name' => 'Samuel Kiprop',
                'team_name' => 'Kakamega Homeboyz',
                'position' => 9,
                'clean_sheets' => 2,
                'appearances' => 20,
                'clean_sheet_percentage' => 10.00,
                'saves' => 45,
                'goals_conceded' => 32,
                'save_percentage' => 58.44,
                'penalties_saved' => 0,
                'penalties_faced' => 1,
                'minutes_played' => 1800,
                'shots_faced' => 118,
                'shots_on_target_faced' => 77,
                'shots_faced_per_game' => 5.90,
                'nationality' => 'Kenyan',
                'age' => 22,
                'height_cm' => 179.00,
                'dominant_hand' => 'Left',
                'is_vipers_player' => false,
            ],
            [
                'goalkeeper_name' => 'Kevin Oduya',
                'team_name' => 'Nairobi City Stars',
                'position' => 10,
                'clean_sheets' => 1,
                'appearances' => 20,
                'clean_sheet_percentage' => 5.00,
                'saves' => 42,
                'goals_conceded' => 34,
                'save_percentage' => 55.26,
                'penalties_saved' => 0,
                'penalties_faced' => 0,
                'minutes_played' => 1800,
                'shots_faced' => 114,
                'shots_on_target_faced' => 76,
                'shots_faced_per_game' => 5.70,
                'nationality' => 'Kenyan',
                'age' => 21,
                'height_cm' => 178.00,
                'dominant_hand' => 'Right',
                'is_vipers_player' => false,
            ],
        ];

        foreach ($cleanSheets as $keeper) {
            CleanSheet::create([
                'season' => '2024/25',
                'league_name' => 'Premier League',
                'goalkeeper_name' => $keeper['goalkeeper_name'],
                'team_name' => $keeper['team_name'],
                'position' => $keeper['position'],
                'clean_sheets' => $keeper['clean_sheets'],
                'appearances' => $keeper['appearances'],
                'clean_sheet_percentage' => $keeper['clean_sheet_percentage'],
                'saves' => $keeper['saves'],
                'goals_conceded' => $keeper['goals_conceded'],
                'save_percentage' => $keeper['save_percentage'],
                'penalties_saved' => $keeper['penalties_saved'],
                'penalties_faced' => $keeper['penalties_faced'],
                'minutes_played' => $keeper['minutes_played'],
                'shots_faced' => $keeper['shots_faced'],
                'shots_on_target_faced' => $keeper['shots_on_target_faced'],
                'shots_faced_per_game' => $keeper['shots_faced_per_game'],
                'nationality' => $keeper['nationality'],
                'age' => $keeper['age'],
                'height_cm' => $keeper['height_cm'],
                'dominant_hand' => $keeper['dominant_hand'],
                'is_vipers_player' => $keeper['is_vipers_player'],
            ]);
        }
    }
}
