<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\GoalkeeperRanking;

class GoalkeeperRankingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $goalkeeperRankings = [
            [
                'goalkeeper_name' => 'Patrick Matasi',
                'team_name' => 'Vipers Academy',
                'position' => 1,
                'appearances' => 20,
                'minutes_played' => 1800,
                'saves' => 68,
                'goals_conceded' => 15,
                'goals_conceded_per_game' => 0.75,
                'save_percentage' => 81.93,
                'clean_sheets' => 12,
                'clean_sheet_percentage' => 60.00,
                'shots_faced' => 156,
                'shots_on_target_faced' => 83,
                'shots_faced_per_game' => 7.80,
                'penalties_saved' => 2,
                'penalties_faced' => 3,
                'penalty_save_percentage' => 66.67,
                'catches' => 45,
                'punches' => 12,
                'distribution_completed' => 180,
                'distribution_attempted' => 195,
                'distribution_accuracy' => 92.31,
                'crosses_claimed' => 28,
                'errors_leading_to_goal' => 1,
                'overall_rating' => 8.50,
                'nationality' => 'Kenyan',
                'age' => 28,
                'height_cm' => 185.50,
                'dominant_hand' => 'Right',
                'is_vipers_player' => true,
            ],
            [
                'goalkeeper_name' => 'Boniface Onyango',
                'team_name' => 'Gor Mahia FC',
                'position' => 2,
                'appearances' => 20,
                'minutes_played' => 1800,
                'saves' => 72,
                'goals_conceded' => 18,
                'goals_conceded_per_game' => 0.90,
                'save_percentage' => 80.00,
                'clean_sheets' => 10,
                'clean_sheet_percentage' => 50.00,
                'shots_faced' => 162,
                'shots_on_target_faced' => 90,
                'shots_faced_per_game' => 8.10,
                'penalties_saved' => 1,
                'penalties_faced' => 2,
                'penalty_save_percentage' => 50.00,
                'catches' => 48,
                'punches' => 15,
                'distribution_completed' => 175,
                'distribution_attempted' => 190,
                'distribution_accuracy' => 92.11,
                'crosses_claimed' => 32,
                'errors_leading_to_goal' => 2,
                'overall_rating' => 8.20,
                'nationality' => 'Kenyan',
                'age' => 30,
                'height_cm' => 188.00,
                'dominant_hand' => 'Right',
                'is_vipers_player' => false,
            ],
            [
                'goalkeeper_name' => 'Duncan Ochieng',
                'team_name' => 'AFC Leopards',
                'position' => 3,
                'appearances' => 20,
                'minutes_played' => 1800,
                'saves' => 65,
                'goals_conceded' => 20,
                'goals_conceded_per_game' => 1.00,
                'save_percentage' => 76.47,
                'clean_sheets' => 8,
                'clean_sheet_percentage' => 40.00,
                'shots_faced' => 148,
                'shots_on_target_faced' => 85,
                'shots_faced_per_game' => 7.40,
                'penalties_saved' => 0,
                'penalties_faced' => 1,
                'penalty_save_percentage' => 0.00,
                'catches' => 42,
                'punches' => 10,
                'distribution_completed' => 168,
                'distribution_attempted' => 185,
                'distribution_accuracy' => 90.81,
                'crosses_claimed' => 25,
                'errors_leading_to_goal' => 1,
                'overall_rating' => 7.80,
                'nationality' => 'Kenyan',
                'age' => 26,
                'height_cm' => 182.00,
                'dominant_hand' => 'Right',
                'is_vipers_player' => false,
            ],
            [
                'goalkeeper_name' => 'Timothy Odhiambo',
                'team_name' => 'Tusker FC',
                'position' => 4,
                'appearances' => 20,
                'minutes_played' => 1800,
                'saves' => 58,
                'goals_conceded' => 22,
                'goals_conceded_per_game' => 1.10,
                'save_percentage' => 72.50,
                'clean_sheets' => 7,
                'clean_sheet_percentage' => 35.00,
                'shots_faced' => 136,
                'shots_on_target_faced' => 80,
                'shots_faced_per_game' => 6.80,
                'penalties_saved' => 1,
                'penalties_faced' => 1,
                'penalty_save_percentage' => 100.00,
                'catches' => 38,
                'punches' => 8,
                'distribution_completed' => 162,
                'distribution_attempted' => 180,
                'distribution_accuracy' => 90.00,
                'crosses_claimed' => 22,
                'errors_leading_to_goal' => 2,
                'overall_rating' => 7.60,
                'nationality' => 'Kenyan',
                'age' => 29,
                'height_cm' => 186.00,
                'dominant_hand' => 'Left',
                'is_vipers_player' => false,
            ],
            [
                'goalkeeper_name' => 'Collins Okoth',
                'team_name' => 'KCB FC',
                'position' => 5,
                'appearances' => 20,
                'minutes_played' => 1800,
                'saves' => 62,
                'goals_conceded' => 24,
                'goals_conceded_per_game' => 1.20,
                'save_percentage' => 72.09,
                'clean_sheets' => 6,
                'clean_sheet_percentage' => 30.00,
                'shots_faced' => 140,
                'shots_on_target_faced' => 86,
                'shots_faced_per_game' => 7.00,
                'penalties_saved' => 0,
                'penalties_faced' => 2,
                'penalty_save_percentage' => 0.00,
                'catches' => 40,
                'punches' => 11,
                'distribution_completed' => 158,
                'distribution_attempted' => 175,
                'distribution_accuracy' => 90.29,
                'crosses_claimed' => 20,
                'errors_leading_to_goal' => 1,
                'overall_rating' => 7.40,
                'nationality' => 'Kenyan',
                'age' => 25,
                'height_cm' => 184.00,
                'dominant_hand' => 'Right',
                'is_vipers_player' => false,
            ],
            [
                'goalkeeper_name' => 'Brian Bwire',
                'team_name' => 'Mathare United',
                'position' => 6,
                'appearances' => 20,
                'minutes_played' => 1800,
                'saves' => 55,
                'goals_conceded' => 26,
                'goals_conceded_per_game' => 1.30,
                'save_percentage' => 67.90,
                'clean_sheets' => 5,
                'clean_sheet_percentage' => 25.00,
                'shots_faced' => 132,
                'shots_on_target_faced' => 81,
                'shots_faced_per_game' => 6.60,
                'penalties_saved' => 1,
                'penalties_faced' => 1,
                'penalty_save_percentage' => 100.00,
                'catches' => 35,
                'punches' => 9,
                'distribution_completed' => 152,
                'distribution_attempted' => 170,
                'distribution_accuracy' => 89.41,
                'crosses_claimed' => 18,
                'errors_leading_to_goal' => 3,
                'overall_rating' => 7.20,
                'nationality' => 'Kenyan',
                'age' => 27,
                'height_cm' => 181.00,
                'dominant_hand' => 'Right',
                'is_vipers_player' => false,
            ],
            [
                'goalkeeper_name' => 'Michael Otieno',
                'team_name' => 'Sofapaka FC',
                'position' => 7,
                'appearances' => 20,
                'minutes_played' => 1800,
                'saves' => 48,
                'goals_conceded' => 28,
                'goals_conceded_per_game' => 1.40,
                'save_percentage' => 63.16,
                'clean_sheets' => 4,
                'clean_sheet_percentage' => 20.00,
                'shots_faced' => 124,
                'shots_on_target_faced' => 76,
                'shots_faced_per_game' => 6.20,
                'penalties_saved' => 0,
                'penalties_faced' => 1,
                'penalty_save_percentage' => 0.00,
                'catches' => 32,
                'punches' => 7,
                'distribution_completed' => 145,
                'distribution_attempted' => 165,
                'distribution_accuracy' => 87.88,
                'crosses_claimed' => 15,
                'errors_leading_to_goal' => 2,
                'overall_rating' => 6.80,
                'nationality' => 'Kenyan',
                'age' => 24,
                'height_cm' => 183.00,
                'dominant_hand' => 'Right',
                'is_vipers_player' => false,
            ],
            [
                'goalkeeper_name' => 'David Owino',
                'team_name' => 'Ulinzi Stars',
                'position' => 8,
                'appearances' => 20,
                'minutes_played' => 1800,
                'saves' => 52,
                'goals_conceded' => 30,
                'goals_conceded_per_game' => 1.50,
                'save_percentage' => 63.41,
                'clean_sheets' => 3,
                'clean_sheet_percentage' => 15.00,
                'shots_faced' => 130,
                'shots_on_target_faced' => 82,
                'shots_faced_per_game' => 6.50,
                'penalties_saved' => 1,
                'penalties_faced' => 2,
                'penalty_save_percentage' => 50.00,
                'catches' => 36,
                'punches' => 8,
                'distribution_completed' => 148,
                'distribution_attempted' => 168,
                'distribution_accuracy' => 88.10,
                'crosses_claimed' => 16,
                'errors_leading_to_goal' => 4,
                'overall_rating' => 6.60,
                'nationality' => 'Kenyan',
                'age' => 23,
                'height_cm' => 180.00,
                'dominant_hand' => 'Right',
                'is_vipers_player' => false,
            ],
            [
                'goalkeeper_name' => 'Samuel Kiprop',
                'team_name' => 'Kakamega Homeboyz',
                'position' => 9,
                'appearances' => 20,
                'minutes_played' => 1800,
                'saves' => 45,
                'goals_conceded' => 32,
                'goals_conceded_per_game' => 1.60,
                'save_percentage' => 58.44,
                'clean_sheets' => 2,
                'clean_sheet_percentage' => 10.00,
                'shots_faced' => 118,
                'shots_on_target_faced' => 77,
                'shots_faced_per_game' => 5.90,
                'penalties_saved' => 0,
                'penalties_faced' => 1,
                'penalty_save_percentage' => 0.00,
                'catches' => 28,
                'punches' => 6,
                'distribution_completed' => 138,
                'distribution_attempted' => 158,
                'distribution_accuracy' => 87.34,
                'crosses_claimed' => 12,
                'errors_leading_to_goal' => 3,
                'overall_rating' => 6.20,
                'nationality' => 'Kenyan',
                'age' => 22,
                'height_cm' => 179.00,
                'dominant_hand' => 'Left',
                'is_vipers_player' => false,
            ],
            [
                'goalkeeper_name' => 'Kevin Oduya',
                'team_name' => 'Nairobi City Stars',
                'position' => 10,
                'appearances' => 20,
                'minutes_played' => 1800,
                'saves' => 42,
                'goals_conceded' => 34,
                'goals_conceded_per_game' => 1.70,
                'save_percentage' => 55.26,
                'clean_sheets' => 1,
                'clean_sheet_percentage' => 5.00,
                'shots_faced' => 114,
                'shots_on_target_faced' => 76,
                'shots_faced_per_game' => 5.70,
                'penalties_saved' => 0,
                'penalties_faced' => 0,
                'penalty_save_percentage' => 0.00,
                'catches' => 25,
                'punches' => 5,
                'distribution_completed' => 132,
                'distribution_attempted' => 152,
                'distribution_accuracy' => 86.84,
                'crosses_claimed' => 10,
                'errors_leading_to_goal' => 5,
                'overall_rating' => 5.80,
                'nationality' => 'Kenyan',
                'age' => 21,
                'height_cm' => 178.00,
                'dominant_hand' => 'Right',
                'is_vipers_player' => false,
            ],
        ];

        foreach ($goalkeeperRankings as $keeper) {
            GoalkeeperRanking::create([
                'season' => '2024/25',
                'league_name' => 'Premier League',
                'goalkeeper_name' => $keeper['goalkeeper_name'],
                'team_name' => $keeper['team_name'],
                'position' => $keeper['position'],
                'appearances' => $keeper['appearances'],
                'minutes_played' => $keeper['minutes_played'],
                'saves' => $keeper['saves'],
                'goals_conceded' => $keeper['goals_conceded'],
                'goals_conceded_per_game' => $keeper['goals_conceded_per_game'],
                'save_percentage' => $keeper['save_percentage'],
                'clean_sheets' => $keeper['clean_sheets'],
                'clean_sheet_percentage' => $keeper['clean_sheet_percentage'],
                'shots_faced' => $keeper['shots_faced'],
                'shots_on_target_faced' => $keeper['shots_on_target_faced'],
                'shots_faced_per_game' => $keeper['shots_faced_per_game'],
                'penalties_saved' => $keeper['penalties_saved'],
                'penalties_faced' => $keeper['penalties_faced'],
                'penalty_save_percentage' => $keeper['penalty_save_percentage'],
                'catches' => $keeper['catches'],
                'punches' => $keeper['punches'],
                'distribution_completed' => $keeper['distribution_completed'],
                'distribution_attempted' => $keeper['distribution_attempted'],
                'distribution_accuracy' => $keeper['distribution_accuracy'],
                'crosses_claimed' => $keeper['crosses_claimed'],
                'errors_leading_to_goal' => $keeper['errors_leading_to_goal'],
                'overall_rating' => $keeper['overall_rating'],
                'nationality' => $keeper['nationality'],
                'age' => $keeper['age'],
                'height_cm' => $keeper['height_cm'],
                'dominant_hand' => $keeper['dominant_hand'],
                'is_vipers_player' => $keeper['is_vipers_player'],
            ]);
        }
    }
}
