<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TopScorer;

class TopScorersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $topScorers = [
            [
                'player_name' => 'John Ochieng',
                'team_name' => 'Vipers Academy',
                'ranking_position' => 1,
                'goals' => 18,
                'assists' => 7,
                'appearances' => 20,
                'goals_per_game' => 0.90,
                'minutes_played' => 1800,
                'shots_on_target' => 45,
                'shots_total' => 78,
                'shot_accuracy' => 57.69,
                'penalties_scored' => 3,
                'penalties_missed' => 1,
                'free_kicks' => 2,
                'headers' => 5,
                'left_foot' => 8,
                'right_foot' => 10,
                'inside_box' => 14,
                'outside_box' => 4,
                'nationality' => 'Kenyan',
                'age' => 22,
                'player_position' => 'Forward',
                'is_vipers_player' => true,
            ],
            [
                'player_name' => 'Michael Kiprop',
                'team_name' => 'Gor Mahia FC',
                'ranking_position' => 2,
                'goals' => 16,
                'assists' => 5,
                'appearances' => 19,
                'goals_per_game' => 0.84,
                'minutes_played' => 1710,
                'shots_on_target' => 38,
                'shots_total' => 65,
                'shot_accuracy' => 58.46,
                'penalties_scored' => 2,
                'penalties_missed' => 0,
                'free_kicks' => 1,
                'headers' => 4,
                'left_foot' => 6,
                'right_foot' => 10,
                'inside_box' => 12,
                'outside_box' => 4,
                'nationality' => 'Kenyan',
                'age' => 24,
                'player_position' => 'Forward',
                'is_vipers_player' => false,
            ],
            [
                'player_name' => 'David Njoroge',
                'team_name' => 'AFC Leopards',
                'ranking_position' => 3,
                'goals' => 14,
                'assists' => 8,
                'appearances' => 18,
                'goals_per_game' => 0.78,
                'minutes_played' => 1620,
                'shots_on_target' => 35,
                'shots_total' => 62,
                'shot_accuracy' => 56.45,
                'penalties_scored' => 1,
                'penalties_missed' => 1,
                'free_kicks' => 0,
                'headers' => 3,
                'left_foot' => 7,
                'right_foot' => 7,
                'inside_box' => 11,
                'outside_box' => 3,
                'nationality' => 'Kenyan',
                'age' => 21,
                'player_position' => 'Forward',
                'is_vipers_player' => false,
            ],
            [
                'player_name' => 'Peter Mwangi',
                'team_name' => 'Tusker FC',
                'ranking_position' => 4,
                'goals' => 13,
                'assists' => 6,
                'appearances' => 17,
                'goals_per_game' => 0.76,
                'minutes_played' => 1530,
                'shots_on_target' => 32,
                'shots_total' => 58,
                'shot_accuracy' => 55.17,
                'penalties_scored' => 2,
                'penalties_missed' => 0,
                'free_kicks' => 1,
                'headers' => 2,
                'left_foot' => 5,
                'right_foot' => 8,
                'inside_box' => 10,
                'outside_box' => 3,
                'nationality' => 'Kenyan',
                'age' => 23,
                'player_position' => 'Midfielder',
                'is_vipers_player' => false,
            ],
            [
                'player_name' => 'James Odhiambo',
                'team_name' => 'KCB FC',
                'ranking_position' => 5,
                'goals' => 12,
                'assists' => 4,
                'appearances' => 16,
                'goals_per_game' => 0.75,
                'minutes_played' => 1440,
                'shots_on_target' => 28,
                'shots_total' => 52,
                'shot_accuracy' => 53.85,
                'penalties_scored' => 1,
                'penalties_missed' => 1,
                'free_kicks' => 0,
                'headers' => 4,
                'left_foot' => 6,
                'right_foot' => 6,
                'inside_box' => 9,
                'outside_box' => 3,
                'nationality' => 'Kenyan',
                'age' => 25,
                'player_position' => 'Forward',
                'is_vipers_player' => false,
            ],
            [
                'player_name' => 'Samuel Kiprotich',
                'team_name' => 'Mathare United',
                'ranking_position' => 6,
                'goals' => 11,
                'assists' => 7,
                'appearances' => 18,
                'goals_per_game' => 0.61,
                'minutes_played' => 1620,
                'shots_on_target' => 26,
                'shots_total' => 48,
                'shot_accuracy' => 54.17,
                'penalties_scored' => 0,
                'penalties_missed' => 0,
                'free_kicks' => 2,
                'headers' => 3,
                'left_foot' => 4,
                'right_foot' => 7,
                'inside_box' => 8,
                'outside_box' => 3,
                'nationality' => 'Kenyan',
                'age' => 20,
                'player_position' => 'Midfielder',
                'is_vipers_player' => false,
            ],
            [
                'player_name' => 'Kevin Oduya',
                'team_name' => 'Sofapaka FC',
                'ranking_position' => 7,
                'goals' => 10,
                'assists' => 5,
                'appearances' => 15,
                'goals_per_game' => 0.67,
                'minutes_played' => 1350,
                'shots_on_target' => 24,
                'shots_total' => 45,
                'shot_accuracy' => 53.33,
                'penalties_scored' => 1,
                'penalties_missed' => 0,
                'free_kicks' => 1,
                'headers' => 2,
                'left_foot' => 5,
                'right_foot' => 5,
                'inside_box' => 7,
                'outside_box' => 3,
                'nationality' => 'Kenyan',
                'age' => 26,
                'player_position' => 'Forward',
                'is_vipers_player' => false,
            ],
            [
                'player_name' => 'Brian Ochieng',
                'team_name' => 'Ulinzi Stars',
                'ranking_position' => 8,
                'goals' => 9,
                'assists' => 3,
                'appearances' => 14,
                'goals_per_game' => 0.64,
                'minutes_played' => 1260,
                'shots_on_target' => 22,
                'shots_total' => 42,
                'shot_accuracy' => 52.38,
                'penalties_scored' => 0,
                'penalties_missed' => 1,
                'free_kicks' => 0,
                'headers' => 3,
                'left_foot' => 4,
                'right_foot' => 5,
                'inside_box' => 6,
                'outside_box' => 3,
                'nationality' => 'Kenyan',
                'age' => 22,
                'player_position' => 'Forward',
                'is_vipers_player' => false,
            ],
            [
                'player_name' => 'Collins Kiprop',
                'team_name' => 'Kakamega Homeboyz',
                'ranking_position' => 9,
                'goals' => 8,
                'assists' => 4,
                'appearances' => 16,
                'goals_per_game' => 0.50,
                'minutes_played' => 1440,
                'shots_on_target' => 20,
                'shots_total' => 38,
                'shot_accuracy' => 52.63,
                'penalties_scored' => 1,
                'penalties_missed' => 0,
                'free_kicks' => 0,
                'headers' => 2,
                'left_foot' => 3,
                'right_foot' => 5,
                'inside_box' => 5,
                'outside_box' => 3,
                'nationality' => 'Kenyan',
                'age' => 24,
                'player_position' => 'Midfielder',
                'is_vipers_player' => false,
            ],
            [
                'player_name' => 'Dennis Kiprotich',
                'team_name' => 'Nairobi City Stars',
                'ranking_position' => 10,
                'goals' => 7,
                'assists' => 2,
                'appearances' => 13,
                'goals_per_game' => 0.54,
                'minutes_played' => 1170,
                'shots_on_target' => 18,
                'shots_total' => 35,
                'shot_accuracy' => 51.43,
                'penalties_scored' => 0,
                'penalties_missed' => 0,
                'free_kicks' => 1,
                'headers' => 1,
                'left_foot' => 4,
                'right_foot' => 3,
                'inside_box' => 4,
                'outside_box' => 3,
                'nationality' => 'Kenyan',
                'age' => 21,
                'player_position' => 'Forward',
                'is_vipers_player' => false,
            ],
        ];

        foreach ($topScorers as $scorer) {
            TopScorer::create([
                'season' => '2024/25',
                'league_name' => 'Premier League',
                'player_name' => $scorer['player_name'],
                'team_name' => $scorer['team_name'],
                'ranking_position' => $scorer['ranking_position'],
                'goals' => $scorer['goals'],
                'assists' => $scorer['assists'],
                'appearances' => $scorer['appearances'],
                'goals_per_game' => $scorer['goals_per_game'],
                'minutes_played' => $scorer['minutes_played'],
                'shots_on_target' => $scorer['shots_on_target'],
                'shots_total' => $scorer['shots_total'],
                'shot_accuracy' => $scorer['shot_accuracy'],
                'penalties_scored' => $scorer['penalties_scored'],
                'penalties_missed' => $scorer['penalties_missed'],
                'free_kicks' => $scorer['free_kicks'],
                'headers' => $scorer['headers'],
                'left_foot' => $scorer['left_foot'],
                'right_foot' => $scorer['right_foot'],
                'inside_box' => $scorer['inside_box'],
                'outside_box' => $scorer['outside_box'],
                'nationality' => $scorer['nationality'],
                'age' => $scorer['age'],
                'player_position' => $scorer['player_position'],
                'is_vipers_player' => $scorer['is_vipers_player'],
            ]);
        }
    }
}
