<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\LeagueStanding;

class LeagueStandingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $teams = [
            [
                'team_name' => 'Vipers Academy',
                'position' => 1,
                'played' => 20,
                'won' => 15,
                'drawn' => 3,
                'lost' => 2,
                'goals_for' => 45,
                'goals_against' => 15,
                'goal_difference' => 30,
                'points' => 48,
                'clean_sheets' => 12,
                'failed_to_score' => 1,
                'points_per_game' => 2.40,
                'form' => 'WWWWD',
                'is_vipers_team' => true,
            ],
            [
                'team_name' => 'Gor Mahia FC',
                'position' => 2,
                'played' => 20,
                'won' => 14,
                'drawn' => 4,
                'lost' => 2,
                'goals_for' => 42,
                'goals_against' => 18,
                'goal_difference' => 24,
                'points' => 46,
                'clean_sheets' => 10,
                'failed_to_score' => 2,
                'points_per_game' => 2.30,
                'form' => 'WDWWW',
                'is_vipers_team' => false,
            ],
            [
                'team_name' => 'AFC Leopards',
                'position' => 3,
                'played' => 20,
                'won' => 12,
                'drawn' => 5,
                'lost' => 3,
                'goals_for' => 38,
                'goals_against' => 20,
                'goal_difference' => 18,
                'points' => 41,
                'clean_sheets' => 8,
                'failed_to_score' => 3,
                'points_per_game' => 2.05,
                'form' => 'WDLWW',
                'is_vipers_team' => false,
            ],
            [
                'team_name' => 'Tusker FC',
                'position' => 4,
                'played' => 20,
                'won' => 11,
                'drawn' => 6,
                'lost' => 3,
                'goals_for' => 35,
                'goals_against' => 22,
                'goal_difference' => 13,
                'points' => 39,
                'clean_sheets' => 7,
                'failed_to_score' => 2,
                'points_per_game' => 1.95,
                'form' => 'DDWWW',
                'is_vipers_team' => false,
            ],
            [
                'team_name' => 'KCB FC',
                'position' => 5,
                'played' => 20,
                'won' => 10,
                'drawn' => 7,
                'lost' => 3,
                'goals_for' => 32,
                'goals_against' => 24,
                'goal_difference' => 8,
                'points' => 37,
                'clean_sheets' => 6,
                'failed_to_score' => 4,
                'points_per_game' => 1.85,
                'form' => 'WWDWL',
                'is_vipers_team' => false,
            ],
            [
                'team_name' => 'Mathare United',
                'position' => 6,
                'played' => 20,
                'won' => 9,
                'drawn' => 8,
                'lost' => 3,
                'goals_for' => 28,
                'goals_against' => 26,
                'goal_difference' => 2,
                'points' => 35,
                'clean_sheets' => 5,
                'failed_to_score' => 5,
                'points_per_game' => 1.75,
                'form' => 'LDWWD',
                'is_vipers_team' => false,
            ],
            [
                'team_name' => 'Sofapaka FC',
                'position' => 7,
                'played' => 20,
                'won' => 8,
                'drawn' => 9,
                'lost' => 3,
                'goals_for' => 26,
                'goals_against' => 28,
                'goal_difference' => -2,
                'points' => 33,
                'clean_sheets' => 4,
                'failed_to_score' => 6,
                'points_per_game' => 1.65,
                'form' => 'DWDLW',
                'is_vipers_team' => false,
            ],
            [
                'team_name' => 'Ulinzi Stars',
                'position' => 8,
                'played' => 20,
                'won' => 7,
                'drawn' => 10,
                'lost' => 3,
                'goals_for' => 24,
                'goals_against' => 30,
                'goal_difference' => -6,
                'points' => 31,
                'clean_sheets' => 3,
                'failed_to_score' => 7,
                'points_per_game' => 1.55,
                'form' => 'WDDLD',
                'is_vipers_team' => false,
            ],
            [
                'team_name' => 'Kakamega Homeboyz',
                'position' => 9,
                'played' => 20,
                'won' => 6,
                'drawn' => 11,
                'lost' => 3,
                'goals_for' => 22,
                'goals_against' => 32,
                'goal_difference' => -10,
                'points' => 29,
                'clean_sheets' => 2,
                'failed_to_score' => 8,
                'points_per_game' => 1.45,
                'form' => 'LDLWD',
                'is_vipers_team' => false,
            ],
            [
                'team_name' => 'Nairobi City Stars',
                'position' => 10,
                'played' => 20,
                'won' => 5,
                'drawn' => 12,
                'lost' => 3,
                'goals_for' => 20,
                'goals_against' => 34,
                'goal_difference' => -14,
                'points' => 27,
                'clean_sheets' => 1,
                'failed_to_score' => 9,
                'points_per_game' => 1.35,
                'form' => 'DLDWL',
                'is_vipers_team' => false,
            ],
        ];

        foreach ($teams as $team) {
            LeagueStanding::create([
                'season' => '2024/25',
                'league_name' => 'Premier League',
                'team_name' => $team['team_name'],
                'position' => $team['position'],
                'played' => $team['played'],
                'won' => $team['won'],
                'drawn' => $team['drawn'],
                'lost' => $team['lost'],
                'goals_for' => $team['goals_for'],
                'goals_against' => $team['goals_against'],
                'goal_difference' => $team['goal_difference'],
                'points' => $team['points'],
                'clean_sheets' => $team['clean_sheets'],
                'failed_to_score' => $team['failed_to_score'],
                'points_per_game' => $team['points_per_game'],
                'form' => $team['form'],
                'status' => 'active',
                'is_vipers_team' => $team['is_vipers_team'],
            ]);
        }
    }
}
